"""empty message

Revision ID: 55afbaf6f6e1
Revises: 3cfe5c26d3bc
Create Date: 2023-02-07 14:33:27.521142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55afbaf6f6e1'
down_revision = '3cfe5c26d3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
